/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Ambulance;

/**
 *
 * @author Anirudh
 */
public class ReportCaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportCaseJPanel
     */
    public ReportCaseJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ExistingCaseJPanel = new javax.swing.JPanel();
        lblAmbulanceWorkArea = new javax.swing.JLabel();
        tblAmbulance = new javax.swing.JScrollPane();
        tblAmbulanceRequest = new javax.swing.JTable();
        NewCaseJPanel = new javax.swing.JPanel();
        lblIncidentType = new javax.swing.JLabel();
        txtIncidentType = new javax.swing.JTextField();
        txtStatusAmb = new javax.swing.JTextField();
        lblStatusAmb = new javax.swing.JLabel();
        lblIncidentType1 = new javax.swing.JLabel();
        lblStatusAmb1 = new javax.swing.JLabel();
        txtPulse = new javax.swing.JTextField();
        txtDiagnosis = new javax.swing.JTextField();
        lblStatusAmb2 = new javax.swing.JLabel();
        lblStatusAmb3 = new javax.swing.JLabel();
        txtBloodPres = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDetails = new javax.swing.JTextArea();
        lblHospitalNAme = new javax.swing.JLabel();
        txtHospitalAdd = new javax.swing.JTextField();
        lblStatusAmb7 = new javax.swing.JLabel();
        lblIncidentType8 = new javax.swing.JLabel();
        txtHospitalCity = new javax.swing.JTextField();
        txtHospitalName = new javax.swing.JTextField();
        lblStatusAmb8 = new javax.swing.JLabel();
        txtHospitalZip = new javax.swing.JTextField();
        txtDoctorName = new javax.swing.JTextField();
        lblStatusAmb9 = new javax.swing.JLabel();
        btnAddNew = new javax.swing.JButton();
        lblCaseID = new javax.swing.JLabel();
        txtCaseID = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblAmbulanceReport = new javax.swing.JLabel();

        lblAmbulanceWorkArea.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblAmbulanceWorkArea.setText("Case Reporting Area");

        tblAmbulanceRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Case ID", "Operator Name", "Victim Name", "Date", "Time", "Diagnosis", "Hospital"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAmbulance.setViewportView(tblAmbulanceRequest);

        javax.swing.GroupLayout ExistingCaseJPanelLayout = new javax.swing.GroupLayout(ExistingCaseJPanel);
        ExistingCaseJPanel.setLayout(ExistingCaseJPanelLayout);
        ExistingCaseJPanelLayout.setHorizontalGroup(
            ExistingCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExistingCaseJPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(ExistingCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAmbulanceWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tblAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        ExistingCaseJPanelLayout.setVerticalGroup(
            ExistingCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExistingCaseJPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblAmbulanceWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tblAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Existing Cases", ExistingCaseJPanel);

        lblIncidentType.setText("Incident Type");

        txtIncidentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIncidentTypeActionPerformed(evt);
            }
        });

        txtStatusAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusAmbActionPerformed(evt);
            }
        });

        lblStatusAmb.setText("Victim Status");

        lblIncidentType1.setText("Diagnosis");

        lblStatusAmb1.setText("Pulse");

        txtPulse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPulseActionPerformed(evt);
            }
        });

        txtDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagnosisActionPerformed(evt);
            }
        });

        lblStatusAmb2.setText("Additional Details");

        lblStatusAmb3.setText("Blood Pressure");

        txtBloodPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPresActionPerformed(evt);
            }
        });

        txtAreaDetails.setColumns(20);
        txtAreaDetails.setRows(5);
        jScrollPane1.setViewportView(txtAreaDetails);

        lblHospitalNAme.setText("Hospital Name");

        txtHospitalAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalAddActionPerformed(evt);
            }
        });

        lblStatusAmb7.setText("Hospital Address");

        lblIncidentType8.setText("Hospital City");

        txtHospitalCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalCityActionPerformed(evt);
            }
        });

        txtHospitalName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalNameActionPerformed(evt);
            }
        });

        lblStatusAmb8.setText("Hospital Zip");

        txtHospitalZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalZipActionPerformed(evt);
            }
        });

        txtDoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorNameActionPerformed(evt);
            }
        });

        lblStatusAmb9.setText("Doctor Name");

        btnAddNew.setText("Add New Record");

        lblCaseID.setText("Case ID");

        txtCaseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaseIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewCaseJPanelLayout = new javax.swing.GroupLayout(NewCaseJPanel);
        NewCaseJPanel.setLayout(NewCaseJPanelLayout);
        NewCaseJPanelLayout.setHorizontalGroup(
            NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewCaseJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddNew)
                .addGap(423, 423, 423))
            .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                        .addComponent(lblCaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(txtCaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                        .addComponent(lblStatusAmb2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                .addComponent(lblStatusAmb3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(txtBloodPres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                    .addComponent(lblStatusAmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(76, 76, 76)
                                    .addComponent(txtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                    .addComponent(lblIncidentType1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(76, 76, 76)
                                    .addComponent(txtDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                    .addComponent(lblStatusAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(76, 76, 76)
                                    .addComponent(txtStatusAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                    .addComponent(lblIncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(76, 76, 76)
                                    .addComponent(txtIncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                .addComponent(lblStatusAmb9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                    .addComponent(lblStatusAmb8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(76, 76, 76)
                                    .addComponent(txtHospitalZip, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                    .addComponent(lblIncidentType8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(76, 76, 76)
                                    .addComponent(txtHospitalCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                    .addComponent(lblStatusAmb7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(76, 76, 76)
                                    .addComponent(txtHospitalAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                    .addComponent(lblHospitalNAme, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(76, 76, 76)
                                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30))))
        );
        NewCaseJPanelLayout.setVerticalGroup(
            NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStatusAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStatusAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIncidentType1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStatusAmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPulse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStatusAmb3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBloodPres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHospitalNAme, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStatusAmb7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHospitalAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIncidentType8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHospitalCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStatusAmb8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHospitalZip, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStatusAmb9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67)
                .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatusAmb2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnAddNew)
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("Add New Case", NewCaseJPanel);

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblAmbulanceReport.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblAmbulanceReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAmbulanceReport.setText("Ambulance Reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblAmbulanceReport, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblAmbulanceReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIncidentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIncidentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIncidentTypeActionPerformed

    private void txtStatusAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusAmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusAmbActionPerformed

    private void txtPulseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPulseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPulseActionPerformed

    private void txtDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagnosisActionPerformed

    private void txtBloodPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPresActionPerformed

    private void txtHospitalAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalAddActionPerformed

    private void txtHospitalCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalCityActionPerformed

    private void txtHospitalNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalNameActionPerformed

    private void txtHospitalZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalZipActionPerformed

    private void txtDoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorNameActionPerformed

    private void txtCaseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaseIDActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExistingCaseJPanel;
    private javax.swing.JPanel NewCaseJPanel;
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAmbulanceReport;
    private javax.swing.JLabel lblAmbulanceWorkArea;
    private javax.swing.JLabel lblCaseID;
    private javax.swing.JLabel lblHospitalNAme;
    private javax.swing.JLabel lblIncidentType;
    private javax.swing.JLabel lblIncidentType1;
    private javax.swing.JLabel lblIncidentType8;
    private javax.swing.JLabel lblStatusAmb;
    private javax.swing.JLabel lblStatusAmb1;
    private javax.swing.JLabel lblStatusAmb2;
    private javax.swing.JLabel lblStatusAmb3;
    private javax.swing.JLabel lblStatusAmb7;
    private javax.swing.JLabel lblStatusAmb8;
    private javax.swing.JLabel lblStatusAmb9;
    private javax.swing.JScrollPane tblAmbulance;
    private javax.swing.JTable tblAmbulanceRequest;
    private javax.swing.JTextArea txtAreaDetails;
    private javax.swing.JTextField txtBloodPres;
    private javax.swing.JTextField txtCaseID;
    private javax.swing.JTextField txtDiagnosis;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtHospitalAdd;
    private javax.swing.JTextField txtHospitalCity;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtHospitalZip;
    private javax.swing.JTextField txtIncidentType;
    private javax.swing.JTextField txtPulse;
    private javax.swing.JTextField txtStatusAmb;
    // End of variables declaration//GEN-END:variables
}
