/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Fire;

import Services.UserAccount.UserAccount;
import UI.MainJFrame;
import java.sql.*;
/**
 *
 * @author tanujverma
 */
public class firadminInterface extends javax.swing.JPanel {

    UserAccount user;
    Connection con;
    /**
     * Creates new form firadminInterface
     */
    public firadminInterface(UserAccount user, Connection con) {
        initComponents();
        this.user = user;
        this.con = con;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFireAdmin = new javax.swing.JLabel();
        btnManageFireMarshal = new javax.swing.JButton();
        btnAssignFire = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnAnalysis = new javax.swing.JButton();

        lblFireAdmin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblFireAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFireAdmin.setText("FIRE ADMIN WORK AREA");

        btnManageFireMarshal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnManageFireMarshal.setText("Manage Fire Marshal");
        btnManageFireMarshal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageFireMarshalActionPerformed(evt);
            }
        });

        btnAssignFire.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAssignFire.setText(" Fire Cases");
        btnAssignFire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignFireActionPerformed(evt);
            }
        });

        btnReports.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnReports.setText("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnAnalysis.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAnalysis.setText("Analysis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFireAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageFireMarshal, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAssignFire, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(273, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFireAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManageFireMarshal)
                    .addComponent(btnAssignFire))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReports)
                    .addComponent(btnAnalysis))
                .addContainerGap(242, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignFireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignFireActionPerformed
        // TODO add your handling code here:
        master_work_queue panel = new master_work_queue(user, con);
        new MainJFrame().replaceSplitPaneChild(this, panel);
    }//GEN-LAST:event_btnAssignFireActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        report_history panel = new report_history(user, con);
        new MainJFrame().replaceSplitPaneChild(this, panel);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnManageFireMarshalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageFireMarshalActionPerformed
        // TODO add your handling code here: --
        FireMarshal_CRUD panel = new FireMarshal_CRUD(user, con);
        new MainJFrame().replaceSplitPaneChild(this, panel);
    }//GEN-LAST:event_btnManageFireMarshalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalysis;
    private javax.swing.JButton btnAssignFire;
    private javax.swing.JButton btnManageFireMarshal;
    private javax.swing.JButton btnReports;
    private javax.swing.JLabel lblFireAdmin;
    // End of variables declaration//GEN-END:variables
}
