/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Fire;

/**
 *
 * @author mehul
 */
public class FireAdminInterface extends javax.swing.JFrame {

    /**
     * Creates new form FireAdminInterface
     */
    public FireAdminInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFireAdmin = new javax.swing.JLabel();
        btnCreateMarshal = new javax.swing.JButton();
        btnAssignFire = new javax.swing.JButton();
        btnAssignRescue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFireAdmin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblFireAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFireAdmin.setText("WELCOME TO FIRE ADMIN WORK AREA");

        btnCreateMarshal.setText("Create Marshal");

        btnAssignFire.setText("Assign Fire Case");

        btnAssignRescue.setText("Assign Rescue Case");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFireAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(btnCreateMarshal)
                .addGap(75, 75, 75)
                .addComponent(btnAssignFire)
                .addGap(75, 75, 75)
                .addComponent(btnAssignRescue)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFireAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateMarshal)
                    .addComponent(btnAssignRescue)
                    .addComponent(btnAssignFire))
                .addGap(0, 365, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignFire;
    private javax.swing.JButton btnAssignRescue;
    private javax.swing.JButton btnCreateMarshal;
    private javax.swing.JLabel lblFireAdmin;
    // End of variables declaration//GEN-END:variables
}
