/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DisasterManagement;

/**
 *
 * @author Anirudh
 */
public class HazMatReport extends javax.swing.JPanel {

    /**
     * Creates new form HazMatReport
     */
    public HazMatReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        ExistingCaseJPanel = new javax.swing.JPanel();
        lblAmbulanceWorkArea = new javax.swing.JLabel();
        tblAmbulance = new javax.swing.JScrollPane();
        tblHazMatRequests = new javax.swing.JTable();
        NewCaseJPanel = new javax.swing.JPanel();
        lblIncidentType = new javax.swing.JLabel();
        txtIncidentType = new javax.swing.JTextField();
        txtStatusAmb = new javax.swing.JTextField();
        lblStatusAmb = new javax.swing.JLabel();
        lblIncidentType1 = new javax.swing.JLabel();
        lblStatusAmb1 = new javax.swing.JLabel();
        txtDiagnosis = new javax.swing.JTextField();
        lblStatusAmb2 = new javax.swing.JLabel();
        lblStatusAmb3 = new javax.swing.JLabel();
        txtBloodPres = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnAddNew = new javax.swing.JButton();
        lblCaseID = new javax.swing.JLabel();
        txtCaseID = new javax.swing.JTextField();
        txtBloodPres1 = new javax.swing.JTextField();
        lblStatusAmb4 = new javax.swing.JLabel();
        lblIncidentType2 = new javax.swing.JLabel();
        txtDiagnosis1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblFullAddress = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDetails1 = new javax.swing.JTextArea();
        lblHazMatReport = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        lblAmbulanceWorkArea.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblAmbulanceWorkArea.setText("Case Reporting Area");

        tblHazMatRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Case ID", "Operator Name", "Date", "Time", "Address", "Substance", "Class", "Est. Damage", "Evacuation No."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAmbulance.setViewportView(tblHazMatRequests);

        javax.swing.GroupLayout ExistingCaseJPanelLayout = new javax.swing.GroupLayout(ExistingCaseJPanel);
        ExistingCaseJPanel.setLayout(ExistingCaseJPanelLayout);
        ExistingCaseJPanelLayout.setHorizontalGroup(
            ExistingCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExistingCaseJPanelLayout.createSequentialGroup()
                .addGroup(ExistingCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExistingCaseJPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblAmbulanceWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ExistingCaseJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tblAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ExistingCaseJPanelLayout.setVerticalGroup(
            ExistingCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExistingCaseJPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblAmbulanceWorkArea, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tblAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Existing Cases", ExistingCaseJPanel);

        lblIncidentType.setText("Incident");

        txtIncidentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIncidentTypeActionPerformed(evt);
            }
        });

        txtStatusAmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusAmbActionPerformed(evt);
            }
        });

        lblStatusAmb.setText("Hazardous Material Name");

        lblIncidentType1.setText("Hazardous Class");

        lblStatusAmb1.setText("No. of people evacuated");

        txtDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagnosisActionPerformed(evt);
            }
        });

        lblStatusAmb2.setText("Additional Details");

        lblStatusAmb3.setText("Total Estimated Damage");

        txtBloodPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPresActionPerformed(evt);
            }
        });

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        btnAddNew.setText("Add New Record");

        lblCaseID.setText("Case ID");

        txtCaseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaseIDActionPerformed(evt);
            }
        });

        txtBloodPres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBloodPres1ActionPerformed(evt);
            }
        });

        lblStatusAmb4.setText("Incident Date");

        lblIncidentType2.setText("Incident Time (24 hr format)");

        txtDiagnosis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagnosis1ActionPerformed(evt);
            }
        });

        lblFullAddress.setText("Full Address");

        txtAreaDetails1.setColumns(20);
        txtAreaDetails1.setRows(5);
        jScrollPane2.setViewportView(txtAreaDetails1);

        javax.swing.GroupLayout NewCaseJPanelLayout = new javax.swing.GroupLayout(NewCaseJPanel);
        NewCaseJPanel.setLayout(NewCaseJPanelLayout);
        NewCaseJPanelLayout.setHorizontalGroup(
            NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewCaseJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddNew)
                .addGap(423, 423, 423))
            .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatusAmb2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                .addComponent(lblCaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(txtCaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStatusAmb4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewCaseJPanelLayout.createSequentialGroup()
                                        .addComponent(lblIncidentType1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(76, 76, 76)
                                        .addComponent(txtDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                            .addComponent(lblStatusAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(76, 76, 76)
                                            .addComponent(txtStatusAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                            .addComponent(lblIncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(76, 76, 76)
                                            .addComponent(txtIncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblStatusAmb3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblStatusAmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(76, 76, 76)
                                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBloodPres1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBloodPres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIncidentType2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFullAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34)
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiagnosis1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                    .addGap(272, 272, 272)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(432, Short.MAX_VALUE)))
        );
        NewCaseJPanelLayout.setVerticalGroup(
            NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatusAmb4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIncidentType2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiagnosis1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                                .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblStatusAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStatusAmb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFullAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIncidentType1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(lblStatusAmb1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblStatusAmb3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBloodPres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NewCaseJPanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(txtBloodPres1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addComponent(lblStatusAmb2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnAddNew)
                .addGap(39, 39, 39))
            .addGroup(NewCaseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewCaseJPanelLayout.createSequentialGroup()
                    .addContainerGap(425, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(92, 92, 92)))
        );

        jTabbedPane1.addTab("Add New Case", NewCaseJPanel);

        lblHazMatReport.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblHazMatReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHazMatReport.setText("HazMat Reports");

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHazMatReport, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHazMatReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIncidentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIncidentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIncidentTypeActionPerformed

    private void txtStatusAmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusAmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusAmbActionPerformed

    private void txtDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagnosisActionPerformed

    private void txtBloodPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPresActionPerformed

    private void txtCaseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaseIDActionPerformed

    private void txtBloodPres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBloodPres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBloodPres1ActionPerformed

    private void txtDiagnosis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosis1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagnosis1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExistingCaseJPanel;
    private javax.swing.JPanel NewCaseJPanel;
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnBack;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAmbulanceWorkArea;
    private javax.swing.JLabel lblCaseID;
    private javax.swing.JLabel lblFullAddress;
    private javax.swing.JLabel lblHazMatReport;
    private javax.swing.JLabel lblIncidentType;
    private javax.swing.JLabel lblIncidentType1;
    private javax.swing.JLabel lblIncidentType2;
    private javax.swing.JLabel lblStatusAmb;
    private javax.swing.JLabel lblStatusAmb1;
    private javax.swing.JLabel lblStatusAmb2;
    private javax.swing.JLabel lblStatusAmb3;
    private javax.swing.JLabel lblStatusAmb4;
    private javax.swing.JScrollPane tblAmbulance;
    private javax.swing.JTable tblHazMatRequests;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextArea txtAreaDetails1;
    private javax.swing.JTextField txtBloodPres;
    private javax.swing.JTextField txtBloodPres1;
    private javax.swing.JTextField txtCaseID;
    private javax.swing.JTextField txtDiagnosis;
    private javax.swing.JTextField txtDiagnosis1;
    private javax.swing.JTextField txtIncidentType;
    private javax.swing.JTextField txtStatusAmb;
    // End of variables declaration//GEN-END:variables
}
