/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Services.SqlConn.SqlConn;
import Services.UserAccount.UserAccount;
import UI.AdminInterface.SystemAdminInterface;
import UI.Ambulance.AmbulanceAdmin;
import UI.Ambulance.Ambulance_work_queue;
import UI.DisasterManagement.DM_work_queue;
import UI.DisasterManagement.Hazmatteamworkarea;
import UI.DisasterManagement.TactTeamworkarea;
import UI.Fire.Fire_work_queue;
import UI.Fire.firadminInterface;
import UI.OperatorHandling.OperatorAdmin;
import UI.OperatorHandling.OperatorMasterWorkQueue;
import UI.Police.Police_Admin;
import UI.Police.Police_work_queue;
import java.sql.*;  
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 *
 * @author Anirudh
 */
public class MainJFrame extends javax.swing.JFrame {

    private UserAccount user; 
    private SqlConn sqlSystem;
    private Connection con;
    private ResultSet rs;
    Statement stmt;
    
    public MainJFrame() {
        initComponents();
        user = new UserAccount();
        sqlSystem = new SqlConn();
        con = sqlSystem.SqlConnDB();
        setExtendedState(getExtendedState()| JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        LoginJPanel = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnLogoutMain = new javax.swing.JButton();
        Container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        LoginJPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, -1));
        LoginJPanel.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 110, -1));
        LoginJPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 109, 110, -1));

        lblUserName.setText("User Name");
        LoginJPanel.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 21, -1, -1));

        lblPassword.setText("Password");
        LoginJPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 86, -1, -1));

        btnLogoutMain.setText("Logout");
        btnLogoutMain.setEnabled(false);
        btnLogoutMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutMainActionPerformed(evt);
            }
        });
        LoginJPanel.add(btnLogoutMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 208, 100, -1));

        jSplitPane1.setLeftComponent(LoginJPanel);

        Container.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(Container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        
        String userName = txtUserName.getText();
        char[] passwordCharArray = txtPassword.getPassword();
        String password = String.valueOf(passwordCharArray);

        try{
        stmt = con.createStatement();  
        rs = stmt.executeQuery("select * from user_account where user_username = '" + userName + "' and user_password = '" + password + "'");  
        rs.next();
        user.setId(rs.getInt("user_id"));
        user.setName(rs.getString("user_name"));
        user.setUserName(rs.getString("user_username"));
        user.setPassword(rs.getString("user_password"));
        user.setRole(rs.getString("user_role"));
        user.setEnterprise_Id(rs.getInt("Enterprise_Id"));
        
        switch (user.getRole()) {
            case "sys":{
                SystemAdminInterface admininteraface = new SystemAdminInterface(user, con);
                jSplitPane1.setRightComponent(admininteraface);
                break;}
            case "opa":{
                OperatorAdmin admininteraface = new OperatorAdmin(user, con);
                jSplitPane1.setRightComponent(admininteraface);
                break;}
            case "fma":{
                firadminInterface admininteraface = new firadminInterface(user, con);
                jSplitPane1.setRightComponent(admininteraface);
                break;}
            case "poa":{
                Police_Admin admininteraface = new Police_Admin(user, con);
                jSplitPane1.setRightComponent(admininteraface);
                break;}
            case "dma":{
                DM_work_queue admininteraface = new DM_work_queue(user, con);
                jSplitPane1.setRightComponent(admininteraface);
                break;}           
            case "aba":{
                AmbulanceAdmin admininteraface = new AmbulanceAdmin(user, con);
                jSplitPane1.setRightComponent(admininteraface);
                break;}             
            case "ope":{
                OperatorMasterWorkQueue admininteraface = new OperatorMasterWorkQueue(user, con);
                jSplitPane1.setRightComponent(admininteraface);
                break;}
            case "fme":{
                Fire_work_queue admininteraface = new Fire_work_queue(user, con);
                jSplitPane1.setRightComponent(admininteraface);
                break;}
            case "poe":{
                Police_work_queue admininteraface = new Police_work_queue(user, con);
                jSplitPane1.setRightComponent(admininteraface);
                break;}
            case "abe":{
                Ambulance_work_queue admininteraface = new Ambulance_work_queue(user, con);
                jSplitPane1.setRightComponent(admininteraface);
                break;}               
            case "hze":{
                Hazmatteamworkarea admininteraface = new Hazmatteamworkarea(user, con);
                jSplitPane1.setRightComponent(admininteraface);
                break;}               
            case "tte":{
                TactTeamworkarea admininteraface = new TactTeamworkarea(user, con);
                jSplitPane1.setRightComponent(admininteraface);
                break;}              
            }
        
        btnLogin.setEnabled(false);
        txtUserName.setEnabled(false);
        txtPassword.setEnabled(false);
        btnLogoutMain.setEnabled(true);
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Enter valid Login credentials\n" + e.getMessage());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutMainActionPerformed
        // TODO add your handling code here:
        
        btnLogoutMain.setEnabled(false);
        txtUserName.setEnabled(true);
        txtPassword.setEnabled(true);
        btnLogin.setEnabled(true);

        txtUserName.setText("");
        txtPassword.setText("");
     
        jSplitPane1.remove(jSplitPane1.getRightComponent());
    }//GEN-LAST:event_btnLogoutMainActionPerformed

    public void replaceSplitPaneChild(JComponent oldChild, JComponent newChild) {
        JSplitPane parent = (JSplitPane) oldChild.getParent();
        int dividerLocation = parent.getDividerLocation();
        parent.remove(oldChild);
        parent.add(newChild);
        parent.setDividerLocation(dividerLocation);
        newChild.revalidate();
        newChild.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JPanel LoginJPanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogoutMain;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
